apiVersion: v1
kind: Service
metadata:
  name: cart-services
  namespace: subbu-1-ns
spec:
  type: LoadBalancer # Use ClusterIP or NodePort based on your requirements
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: cart